### ISSUE TITLE
Ripple doesn't work on bootstrap modal

### ISSUE THREAD

**Issue by rohinarya12** [luncheon/ripplet.js#4]
Hi,

Whenever I put a ripple inside of a bootstrap modal, it does not display on the button. This is maybe because on bootstrap model, it has z-index of 240 so the ripple could maybe be just below the modal or something.

Also, I love this library, thanks for making it!

**Comment by luncheon** [comment]
@rohinarya12 
Please specify `className` option and set `z-index` to that CSS class.
Or try `appendTo: "parent"` option.

And thank you for loving this library!

**Comment by rohinarya12** [comment]
The second option with `ripplet.defaultOptions.appendTo = 'parent'` worked!  This is definitely the best looking waves library :D!
