### ISSUE TITLE
transform animation not playing on chrome in react

### ISSUE THREAD

**Issue by ryansheehan** [luncheon/ripplet.js#6]
Not sure how I am misusing this library, but everything looks and behaves correctly on Firefox.  When using on chrome, however, the transform animation will not play.  The opacity animation seems to play fine.  What is odd is that the demo site plays fine on chrome.  I assume the demo site is running the same 0.3.0 version.

**Comment by luncheon** [comment]
I would like to see the code and the behavior.
Can you create an environment to reproduce it?
CodePen, Plunker, CodeSandbox, StackBlitz, GitHub Pages, or anything else.

**Comment by ryansheehan** [comment]
I was unable to reproduce the issue in isolation.  I've spent my whole morning on this!  I event brought in your raw source so I could debug at every step of the way.

You ever have one of those experiences where code doesn't behave like it should, and you start to get desperate?  Finally you're reduced to commenting out large swaths of your code base just to try and hone in on where the issue exists; I call this, _"playing battleship"_ with your code.

So I start trying to _battleship_ my code, and suddenly things start to work!  Slowly, I start bringing code back to life in order to try and narrow down the offending lines.  It's going to break again eventually... right?  

NOPE!

Everything works perfectly.  `transition: transform` starts working suddenly, and beautifully, on chrome.  Never changed a thing.

Now I am stuck here tearing my hair out trying to figure out how this possible.  My current theory is a rogue neutrino from a gamma ray burst in the Virgo super cluster just hit my computer.  I don't know...

Thanks for the quick response, and cheers on a great package!  Thanks!

**Comment by luncheon** [comment]
It's strange... but strange things happen more often, in reality than in fiction.
I get hit by neutrinos every so often, too. Neutrinos are invisible to our eyes. So...
So please let me know when it reproduces in isolation.
(Seriously, it's really strange that Chrome and Firefox work differently.)
