### ISSUE TITLE
Disable right click for ripple effect?

### ISSUE THREAD

**Issue by AgentSmith0** [luncheon/ripplet.js#8]
Hi, is there a way to disable the ripple effect for right click events, to only allow left click and touch input?
Thank you!

**Comment by luncheon** [comment]
See the `button` property of the `PointerEvent` or `MouseEvent`.

```ts
myButton.addEventListener("pointerdown", event => {
  if (event.button === 0) { // left click or touch
    ripplet(event);
  }
});
```

**Comment by AgentSmith0** [comment]
Thank you!
