### ISSUE TITLE
Option to set class for parent of ripple element

### ISSUE THREAD

**Issue by AgentSmith0** [luncheon/ripplet.js#9]
It would be nice to have an option to set the class for the parent of the ripple effect, which can be set with the option `className` already. This would make styling much easier.

**Comment by luncheon** [comment]
`ripplet()` returns the container element of the generated ripple element.
`className` can be set with the following code:

```ts
const rippleContainer = ripplet({ ... });
rippleContainer.className = "...";
```

But for what use cases?

**Comment by AgentSmith0** [comment]
I use it to add a border radius to the ripple container element. Thank you for your help!
